### ISSUE TITLE
a personal question

### ISSUE THREAD

**Issue by sisyphusman** [johnpayne-dev/MinecraftC#21]
Hello
I pay my respects to your work
I'd like to ask you a question

1. How long has it been since you started programming? (Because my dream is to be a game programmer. I wonder how long it takes to have skills like you)

3. Did you develop the logic of Minecraft C by yourself? Or is it based on other references?

I shouldn't write this here, but I was curious about your work 
I'd appreciate it if you could answer

P.S. If you answer, I'll delete this post right away

**Comment by johnpayne-dev** [comment]
1. It's been about 5 or 6 years since I started programming. If you're looking for where to start on game development, I recommend learning Python and pygame or Lua and Love2d.

2. It's a port from the original java code, so the logic is the exact same as the original game (with some minor exceptions). The raytracing and mods of course are added logic.
