### ISSUE TITLE
Can this client build to android and iOS?

### ISSUE THREAD

**Issue by codingwatching** [johnpayne-dev/MinecraftC#4]
Hi @johnpayne-dev 
I just see this client and want to test it on an android device, is this possible, and how to build it on an android device?
(I think we can implement touch control later)

**Comment by johnpayne-dev** [comment]
In its current state, no. It uses OpenGL 1.1, which is only compatible on PC devices. I had plans to create a compatibility version of this project where I would rewrite the graphics backend to OpenGL ES so it could work on mobile, but I've halted progress on this project indefinitely since my life has just gotten very busy.
